### ISSUE TITLE
Jekyll-4 support

### ISSUE THREAD

**Issue by bgruening** [iBug/jekyll-environment-variables#2]
Is `jekyll-environment-variables` supposed to work with Jekyll-4 or is any new release planned?
According to https://rubygems.org/gems/jekyll-environment-variables >=3,<4 is supported.

**Comment by iBug** [comment]
Thanks a lot for bringing this up. I didn't even know that Jekyll 4 had been released.

Rest assured, the code is fully compatible with Jekyll 4 as I've just verified. A new version `1.0.1` has been released onto RubyGems, changing the gemspec to allow usage in conjunction with Jekyll 4.

**Comment by bgruening** [comment]
Cool, thanks a lot!
