### ISSUE TITLE
Add dotenv .env support

### ISSUE THREAD

**Issue by pke** [iBug/jekyll-environment-variables#3]
Would be nice if this plugin would use the "dotenv" gem and load it for even more flexible jekyll configs.

`require 'dotenv/load'`

**Comment by iBug** [comment]
Sounds like an overkill to me. If you can pass variables in an external file, why not through an extra config file? Jekyll has long supported loading multiple config files at once like this:

```shell
jekyll build --config _config.yml,_extra.yml
```

**Comment by pke** [comment]
The scenario is to be able to configure the site output using env vars. The config file stays the same, that's the whole reason to use this package. 

I have patched my own version to load `dotenv` and that's all the flexibility I need right now.
